Models/Entities/SAUniversity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudentLoan.Models
{
    public class SAUniversity
    {
        public int SAUniversityId { get; set; }
        [Required(ErrorMessage = "Enter a university name")]
        public string Name { get; set; }
    
        public virtual ICollection<SAUniCourse> UniCourses { get; set; }
    }
}

Controllers/SAUniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentLoan.Models;
using StudentLoan.Models.ViewModels;
using StudentLoan.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StudentLoan.Controllers
{
    [Authorize(Roles = "Admins")]
    public class SAUniversityController : Controller
    {
        private readonly IRepositoryWrapper _repository;
        private string message{get;set;}

        public SAUniversityController(IRepositoryWrapper wrapper)
        {
            _repository = wrapper;
           
        }
        [AllowAnonymous]
        public IActionResult PriorityAreas()
        {
            ViewData["Message"] = message;
            return View(_repository.University.FindAll().OrderBy(p => p.Name));
        }
        [AllowAnonymous]
        public IActionResult Courses(int id, string search)
        {
            ViewData["CurrentFilter"] = search;

            if (search == null)
                search = "";

            SAUniversity uni = _repository.University.GetById(id);
            IEnumerable<SAUniCourse> i =_repository.University.GetVarsityCourseList(id,search);

            UniversityCoursesViewModel viewModel = new UniversityCoursesViewModel
            {
                Items = i,
                SAUniversity = uni
            };

                return View(viewModel);
        }
        
        public IActionResult Add()
        {
            List<SACourses> list = new List<SACourses>();
            list = _repository.Course.FindAll().ToList();
            ViewBag.List = list;
            return View();

        }
        [HttpPost]
        public IActionResult Add(SAUniversity varsity)
        {           
            if (ModelState.IsValid)
            {
                try
                {
                    _repository.University.Create(varsity);
                    _repository.University.Save();
                    message = "University successfully added.";
                    return RedirectToAction("PriorityAreas");
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to add University. Try again and if the problem persists, see your system administrator.");
                }
            }
            return View();
        }

        public IActionResult Edit(int id)
        {
            List<SACourses> list = new List<SACourses>();
            list = _repository.Course.FindAll().ToList();
            ViewBag.List = list;
            var u = _repository.University.GetById(id);
            return View(u);
        }
        [HttpPost]
        public IActionResult Edit(SAUniversity varsity)
        {  
            
            if (ModelState.IsValid)
            {
                try
                {
                    _repository.University.Update(varsity);                
                    _repository.University.Save();
                    message = "University successfully updated.";
                    return RedirectToAction("PriorityAreas");
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(varsity);
        }
 
        public IActionResult Delete(int id)
        {
            return View(_repository.University.GetById(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteUni(SAUniversity varsity)
        {
            if(varsity !=null)
            {
                _repository.University.Delete(varsity);
                _repository.University.Save();
                message = "University successfully deleted.";
                return RedirectToAction("PriorityAreas");
            }
            else
            {
                ViewBag.ErrorMessage = "Unable to Delete university";
                return View(varsity);
            }
        }

    }
}

Views/SAUniversity/Add.cshtml
@model SAUniversity
@{
    ViewData["Title"] = "Add University";
}

<h2>
    Add a University
</h2>
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Add">

            <div class="form-group">
                <label asp-for="@Model.Name"></label>
                <div><span asp-validation-for="@Model.Name" class="text-danger"></span></div>
                <input asp-for="@Model.Name" class="form-control" />
            </div>
            <div class="form-group">
            <label>Add Courses</label>
             <table class="table table-bordered">
            @foreach (var c in ViewBag.List)
            {

               <tr>
                   <td>
                       <input type="hidden" asp-for="@Model.UniCourses"/>
                       <input type="checkbox" value="@c.SACoursesId" name="@c.Course" />   

                   </td>
                   <td>
                       @c.Course
                   </td>
               </tr>
            }
                </table>
        </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-controller="SAUniversity" asp-action="PriorityAreas">Back to List</a>
</div>

Views/SAUniversity/Courses.cshtml
@model UniversityCoursesViewModel
@{
    ViewData["Title"] = Model.SAUniversity.Name + " Courses";
    Layout = "_Layout";
}
<div>
    <h2>@Model.SAUniversity.Name Courses</h2>
    <p>Courses that are sponsored from this university</p>
    <div>
        <form asp-action="Courses" method="get">

            <p>
                Search course: <input type="text" name="search" value="@ViewData["CurrentFilter"]" />
                <input type="submit" value="search" class="btn btn-primary" />
                <a class="btn btn-primary" asp-controller="SAUniversity" asp-action="Courses">Back to Full list</a>
            </p>

        </form>
    </div>
    <table>
        <thead>
            <tr>
                <th>
                   Field
                </th>
                <th>
                    Course
                </th>
                <th>
                    Undergraduate
                </th>
                <th>
                    Postgraduate
                </th>  
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model.Items)
            {
                <tr>
                    <td>
                        @c.Course.Field
                    </td>
                    <td>
                        @c.Course.Course
                    </td>
                    <td>
                        @c.Course.Undergrad
                    </td>
                    <td>
                        @c.Course.Postgrad
                    </td>
                </tr>
            }
            @if(Model.Items.Count() == 0)
            {
               <tr>No Courses for this university</tr>
            }
        </tbody>
    </table>
    <p><a asp-controller="SAUniversity" asp-action="PriorityAreas">Back to List</a></p>
</div>

Views/SAUniversity/Delete.cshtml
@model SAUniversity
@{ 
    ViewData["Title"] = "Delete University";
}
<h2>Delete University</h2>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<h4>Are you sure you want to delete this university?</h4>
<div>
    <p style="color: red; font-weight:400;">
        @Model.Name
    </p>
    <form method="post" asp-action="Delete">
        <input type="hidden" asp-for="SAUniversityId"/>
        <input type="submit" value="Delete" class="btn btn-dark"/> |
        <a asp-controller="SAUniversity" asp-action="PriorityAreas">Back to List</a>
    </form>
</div>

Views/SAUniversity/Edit.cshtml
@model SAUniversity
@{
    ViewData["Title"] = "Edit University";
}

<h2>
    Edit University
</h2>
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Edit"  multiple="multiple" class="form-control">
            <div class="form-group">
                <label asp-for="@Model.Name"></label>
                <div><span asp-validation-for="@Model.Name" class="text-danger"></span></div>
                
                <input asp-for="@Model.Name" class="form-control" />
            </div>
            <div class="form-group">
                <label>Courses</label>
                 <table class="table table-bordered">
                @foreach (var c in ViewBag.List)
                {
                    
                   <tr>
                       <td>
                           <input type="hidden" asp-for="@Model.UniCourses"/>
                           <input type="checkbox" value="@c.SACoursesId" name="@c.Course" />    
                          
                       </td>
                       <td >
                           @c.Course
                       </td>
                   </tr> 
                }
                    </table>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.SAUniversityId"/>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-controller="SAUniversity" asp-action="PriorityAreas">Back to List</a>
</div>

Views/SAUniversity/PriorityAreas.cshtml
@model IEnumerable<SAUniversity>
@{
    ViewData["Title"] = "Priority Areas";
    Layout = "_Layout";
}
@if (ViewData["Message"] != null)
{
    <div class="alert alert-info alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        @ViewData["Message"]
    </div>

}

<div data-aos="fade-up">

        <h2>Prioritization of scholarship for South African Institutes - 2021</h2>
        @if (User.Identity.IsAuthenticated && User.IsInRole("Admins"))
        {
            <p><a asp-controller="SAUniversity" asp-action="Add">Add University</a></p>
        }
        <p>The following is a list of Universities with courses that will be priorities at the specific university. Non priority courses will only be considered after the priority courses. Priority courses are based on the priority sectors that have been identified in the STLA Diagnostic Report.</p>

        <p>These sectors are: </p>
        <ul>
            <li>Manufacturing</li>
            <li>Tourism Services</li>
            <li>Technology and Creative Industries, and</li>
            <li>Agriculture</li>
        </ul>
        <p>Prioritization of these sectors is based on the following criteria: </p>
        <ul>
            <li>GDP growth potential</li>
            <li>High comparative advantage</li>
            <li>High value chain</li>
            <li>High multiplier effect</li>
        </ul>

    <div class="row">

        @foreach (SAUniversity u in Model)
        {
        <div class="col-lg-4">
            <div class="box" data-aos="fade-up" data-aos-delay="200">
                <a asp-controller="SAUniversity" asp-action="Courses" asp-route-id="@u.SAUniversityId"><h3 class="card-text">@u.Name</h3></a>              
            </div>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admins"))
            {
                <hr />

                <p><a class="green" asp-controller="SAUniversity" asp-action="Edit" asp-route-id="@u.SAUniversityId">Edit University</a></p>
                <p><a class="red" asp-controller="SAUniversity" asp-action="Delete" asp-route-id="@u.SAUniversityId">Delete University</a></p>
            }
        </div>
        }

    </div>

</div>