Controllers/ApplyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentLoan.Models;
using StudentLoan.Models.Entities;
using StudentLoan.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentLoan.Controllers
{
    public class ApplyController : Controller
    {
        private readonly IRepositoryWrapper _repository;

        public ApplyController(IRepositoryWrapper wrapper)
        {
            _repository = wrapper;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admins")]
        public IActionResult ApplicationDetails(int id)
        {

            return View(_repository.Application.GetById(id));
        }
        [Authorize(Roles="Admins")]
        public IActionResult List()
        {
            return View(_repository.Application.FindAll());
        }
        private void PopulateGender()
        {
            ViewBag.Gender = new SelectList(_repository.Gender.FindAll(), "GenderName", "GenderName",null);

        }
        private void PopulateOccupation()
        {
            ViewBag.Occupation = new SelectList(_repository.Occupation.FindAll(),"OccupationName", "OccupationName",null);
        }
        private void PopulateMarital()
        {
            ViewBag.Marital = new SelectList(_repository.MaritalStatus.FindAll(), "MaritlStatusName", "MaritlStatusName", null);

        }
        private void PopulateCourse()
        {
            ViewBag.Course = new SelectList(_repository.Course.FindAll(), "Course", "Course", null);
        }
        private void PopulateUni()
        {
            ViewBag.Uni = new SelectList(_repository.University.FindAll(), "Name", "Name", null);
        }

        [Authorize(Roles="Applicant")]
        public IActionResult Apply()
        {
            PopulateCourse();
            PopulateGender();
            PopulateMarital();
            PopulateOccupation();
            PopulateUni();

            return View();
        }
        [HttpPost]
        public IActionResult Apply(Application app)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _repository.Application.Create(app);
                    _repository.Application.Save();
                    return RedirectToAction("ApplicationComplete");
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to submit application. Try again and if the problem persists, send an email to nobody@example.com");
                }
            }

            PopulateCourse();
            PopulateGender();
            PopulateMarital();
            PopulateOccupation();
            PopulateUni();

            return View();
            
        }
        [HttpPost]
        public IActionResult Delete(Application app)
        {
            if (app != null)
            {

                _repository.Application.Delete(app);
                _repository.Application.Save();

                return RedirectToAction("List");
            }
            else
            {
                ViewBag.ErrorMessage = "Unable to Delete Application";
                return View(app);
            }
        }
                      
        public IActionResult  ApplicationComplete()
        {
            return View();
        }
    }
}

Views/Shared/UniversityDetails.cshtml
@model SAUniversity
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewBag.Title</title>

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
        <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
        <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
        <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <!-- =======================================================
    * Template Name: FlexStart - v1.4.0
    * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <img src="~/assets/img/logo.png" alt="">
                <span>STLA</span>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a class="nav-link scrollto" asp-controller="SAUniversity" asp-action="PriorityAreas">Priority Areas</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Apply" asp-action="Index">Apply</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Home" asp-action="About">About STLA</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link scrollto">Hello, @User.Identity.Name</a></li>
                        <li><form class="" method="post" asp-action="Logout" asp-controller="Account">
                            <button type="submit" class="btn getstarted scrollto">Log out</button>
                        </form></li>
                    }
                    else
                    {
                        <li>
                            <a class="nav-link scrollto" asp-controller="Account" asp-action="Register">
                                Register
                            </a>
                        </li>
                        <li>
                            <a class="getstarted scrollto" asp-controller="Account" asp-action="Login">
                                Log In
                            </a>
                        </li>
                    }
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
</header><!-- End Header -->
    <!-- ======= Hero Section ======= -->

    <div id="hero" class="hero">

        <div id="content" class="container" style="padding-top:110px;">
            @RenderBody()
        </div>
           
    </div><!-- End Hero -->                    

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>

</html>